[tool.bumpversion]
current_version = "0.7.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]

[[tool.bumpversion.files]]
filename = "package.json"
search = '"name": "zenzic-temp-docs",\n  "version": "\\d+\\.\\d+\\.\\d+",'
replace = '"name": "zenzic-temp-docs",\n  "version": "{new_version}",'
regex = true

[[tool.bumpversion.files]]
filename = "package-lock.json"
search = '"name": "zenzic-temp-docs",\n  "version": "\\d+\\.\\d+\\.\\d+",'
replace = '"name": "zenzic-temp-docs",\n  "version": "{new_version}",'
regex = true

[[tool.bumpversion.files]]
filename = "package-lock.json"
search = '"": {\n      "name": "zenzic-temp-docs",\n      "version": "\\d+\\.\\d+\\.\\d+",'
replace = '"": {\n      "name": "zenzic-temp-docs",\n      "version": "{new_version}",'
regex = true

[[tool.bumpversion.files]]
filename = "docusaurus.config.ts"
search = "'{current_version}'"
replace = "'{new_version}'"

[[tool.bumpversion.files]]
filename = "docusaurus.config.ts"
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "README.md"
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "README.it.md"
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "RELEASE.md"
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "RELEASE.it.md"
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "i18n/en/code.json"
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "i18n/it/code.json"
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "src/components/Homepage/Hero.tsx"
search = "v{current_version}"
replace = "v{new_version}"

[[tool.bumpversion.files]]
filename = "src/components/Homepage/Quickstart.tsx"
search = "zenzic {current_version}"
replace = "zenzic {new_version}"

[[tool.bumpversion.files]]
filename = "src/pages/index.tsx"
search = '"softwareVersion": "{current_version}"'
replace = '"softwareVersion": "{new_version}"'

[[tool.bumpversion.files]]
filename = "docs/how-to/configure-ci-cd.mdx"
search = 'version: "{current_version}"'
replace = 'version: "{new_version}"'

[[tool.bumpversion.files]]
filename = "i18n/it/docusaurus-plugin-content-docs/current/how-to/configure-ci-cd.mdx"
search = 'version: "{current_version}"'
replace = 'version: "{new_version}"'
