# SPDX-FileCopyrightText: 2025 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0

# Read the Docs configuration for Zensical
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

  commands:
    - python -m pip install uv
    - uvx zensical build -f zensical.toml
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
