version = 1

[[annotations]]
path = ["package.json", "package-lock.json", "tsconfig.json", ".markdownlint-cli2.jsonc", "**/*_category_.json", "i18n/**/*.json", "uv.lock"]
SPDX-FileCopyrightText = "2026 PythonWoods <dev@pythonwoods.dev>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["static/**", "docs/**/assets/**", "docs-it/**/assets/**", "i18n/**/assets/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 PythonWoods <dev@pythonwoods.dev>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["blog/**", "docs/**/*.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 PythonWoods <dev@pythonwoods.dev>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["README.md", "CONTRIBUTING.md", "CODE_OF_CONDUCT.md", "SECURITY.md", "RELEASE.md", "NOTICE", "LICENSE"]
SPDX-FileCopyrightText = "2026 PythonWoods <dev@pythonwoods.dev>"
SPDX-License-Identifier = "Apache-2.0"
