# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0

name: Zenzic Docs CI

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'static/**'
      - 'scripts/**'
      - 'zensical.toml'
      - '.zenzic.toml'
      - '.github/workflows/ci.yml'

permissions:
  contents: read

concurrency:
  group: docs-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6

      - name: Install dependencies
        run: uv sync

      - name: Build docs
        run: uv run zensical build
