# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0

name: Zenzic Docs Quality Gate

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  quality-gate:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run Zenzic Quality Gate
        uses: PythonWoods/zenzic-action@16d64c6043d90d5ad10fa8b1efe48f489efbd605 # v2.0.0
        with:
          strict: 'true'
          upload-sarif: 'true'
