# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0

name: Zenzic Docs Quality Gate

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  quality-gate:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Run Zenzic Quality Gate
        uses: PythonWoods/zenzic-action@d8f866625a36f8ccaea69a12a81a83ff65604a1e # v2.2.0
        with:
          version: "0.15.0"
          strict: 'true'
          upload-sarif: 'true'
